import Foundation
import Testing
@testable import GerberKit

@Test func parsesLinesFlashesArcsAndRegions() throws {
    let source = """
    G04 generated by test*
    %FSLAX24Y24*%
    %MOMM*%
    %ADD10C,0.2000*%
    %ADD11R,1.0000X2.0000*%
    D10*
    X10000Y20000D02*
    X30000Y20000D01*
    G03X30000Y40000I0J10000D01*
    D11*
    X50000Y50000D03*
    G01*
    G36*
    X0Y0D02*
    X10000Y0D01*
    X10000Y10000D01*
    X0Y10000D01*
    X0Y0D01*
    G37*
    M02*
    """

    let layer = try GerberParser().parse(data: Data(source.utf8), fileName: "board.GTL")
    #expect(layer.kind == .copper(side: .top, index: nil))
    #expect(layer.primitives.count == 4)

    guard case let .line(start, end, width, _) = layer.primitives[0] else {
        Issue.record("First primitive was not a line")
        return
    }
    #expect(start == Point2D(x: 1, y: 2))
    #expect(end == Point2D(x: 3, y: 2))
    #expect(abs(width - 0.2) < 0.000_001)

    guard case let .flash(center, shape, _) = layer.primitives[2] else {
        Issue.record("Third primitive was not a flash")
        return
    }
    #expect(center == Point2D(x: 5, y: 5))
    #expect(shape == .rectangle(width: 1, height: 2))
}

@Test func honorsInchesClearPolarityAndStepRepeat() throws {
    let source = """
    %FSLAX24Y24*%
    %MOIN*%
    %ADD10C,0.0100*%
    %LPC*%
    %SRX2Y2I1.0J0.5*%
    D10*
    X10000Y10000D03*
    %SR*%
    M02*
    """
    let layer = try GerberParser().parse(data: Data(source.utf8), fileName: "repeat.gbr")
    #expect(layer.primitives.count == 4)
    #expect(layer.primitives.allSatisfy { $0.polarity == .clear })
    let centers = layer.primitives.compactMap { primitive -> Point2D? in
        guard case let .flash(center, _, _) = primitive else { return nil }
        return center
    }
    #expect(centers.contains(Point2D(x: 25.4, y: 25.4)))
    #expect(centers.contains { abs($0.x - 50.8) < 0.000_001 && abs($0.y - 38.1) < 0.000_001 })
}

@Test func parsesEasyEDAExcellon() throws {
    let source = """
    ;TYPE=PLATED
    M48
    METRIC,LZ,000.000000
    T01C0.304800
    T02C1.200000
    %
    G90
    T01
    X5.588Y17.399
    T02
    X10.0Y20.0
    M30
    """
    let hits = try ExcellonParser().parse(data: Data(source.utf8), fileName: "Drill_PTH_Through.DRL")
    #expect(hits.count == 2)
    #expect(hits[0] == DrillHit(center: Point2D(x: 5.588, y: 17.399), diameter: 0.3048, plated: true))
    #expect(hits[1].diameter == 1.2)
}
