import Foundation
import Testing
@testable import GerberKit

@Test func prefersJLCPCBProductionSetOverEnclosedOriginalZIP() throws {
    let files = [
        ZipEntry(name: "GNSS/YG/original.zip", data: Data("not opened".utf8)),
        ZipEntry(name: "GNSS/ok/tl", data: jlcLayer("tl", body: "X0Y0D02*\nX100000Y0D01*")),
        ZipEntry(name: "GNSS/ok/bl", data: jlcLayer("bl", body: "X0Y50000D02*\nX100000Y50000D01*")),
        ZipEntry(name: "GNSS/ok/to", data: jlcLayer("to", body: "X10000Y10000D03*")),
        ZipEntry(name: "GNSS/ok/ko", data: jlcLayer("ko", body: """
            X0Y0D02*
            X100000Y0D01*
            X100000Y50000D01*
            X0Y50000D01*
            X0Y0D01*
            """)),
        ZipEntry(name: "GNSS/ok/drl", data: jlcLayer("drl", body: "X50000Y25000D03*")),
        ZipEntry(name: "GNSS/ok/helper.tgz", data: Data(repeating: 0, count: 16))
    ]

    let document = try FabricationPackageLoader().load(files: files, name: "JLC review")

    #expect(document.packageRole == .jlcpcbProduction)
    #expect(document.enclosedSourceArchives == ["GNSS/YG/original.zip"])
    #expect(document.layers.contains { $0.kind == .copper(side: .top, index: nil) })
    #expect(document.layers.contains { $0.kind == .copper(side: .bottom, index: nil) })
    #expect(document.layers.contains { $0.kind == .outline })
    #expect(document.drills.count == 1)
    #expect(abs(document.bounds.width - 10) < 0.001)
    #expect(abs(document.bounds.height - 5) < 0.001)
}

@Test func opensAGerberSetInsideAGenericNestedZIP() throws {
    let inner = storedZIP([
        ("nested.GTL", genericLayer(body: "X0Y0D02*\nX100000Y0D01*")),
        ("nested.GKO", genericLayer(body: """
            X0Y0D02*
            X100000Y0D01*
            X100000Y50000D01*
            X0Y50000D01*
            X0Y0D01*
            """))
    ])

    let document = try FabricationPackageLoader().load(
        files: [ZipEntry(name: "delivery/fabrication.zip", data: inner)],
        name: "delivery"
    )

    #expect(document.packageRole == .nestedArchive)
    #expect(document.name == "fabrication")
    #expect(document.layers.contains { $0.kind == .outline })
    #expect(document.enclosedSourceArchives == ["delivery/fabrication.zip"])
}

private func genericLayer(body: String) -> Data {
    Data("""
    G04 generated by nested archive test*
    %FSLAX24Y24*%
    %MOMM*%
    %ADD10C,0.2000*%
    D10*
    \(body)
    M02*
    """.utf8)
}

private func jlcLayer(_ name: String, body: String) -> Data {
    Data("""
    G04 -- output software:jlccam pro v3.4.8 *
    G04 -- layer:\(name)*
    %FSLAX24Y24*%
    %MOMM*%
    %ADD10C,0.2000*%
    D10*
    \(body)
    M02*
    """.utf8)
}

func storedZIP(_ files: [(name: String, data: Data)]) -> Data {
    var archive = Data()
    var directory = Data()

    for file in files {
        let name = Data(file.name.utf8)
        let offset = UInt32(archive.count)
        let checksum = crc32(file.data)

        archive.appendLE(UInt32(0x0403_4B50))
        archive.appendLE(UInt16(20))
        archive.appendLE(UInt16(0))
        archive.appendLE(UInt16(0))
        archive.appendLE(UInt16(0))
        archive.appendLE(UInt16(0))
        archive.appendLE(checksum)
        archive.appendLE(UInt32(file.data.count))
        archive.appendLE(UInt32(file.data.count))
        archive.appendLE(UInt16(name.count))
        archive.appendLE(UInt16(0))
        archive.append(name)
        archive.append(file.data)

        directory.appendLE(UInt32(0x0201_4B50))
        directory.appendLE(UInt16(20))
        directory.appendLE(UInt16(20))
        directory.appendLE(UInt16(0))
        directory.appendLE(UInt16(0))
        directory.appendLE(UInt16(0))
        directory.appendLE(UInt16(0))
        directory.appendLE(checksum)
        directory.appendLE(UInt32(file.data.count))
        directory.appendLE(UInt32(file.data.count))
        directory.appendLE(UInt16(name.count))
        directory.appendLE(UInt16(0))
        directory.appendLE(UInt16(0))
        directory.appendLE(UInt16(0))
        directory.appendLE(UInt16(0))
        directory.appendLE(UInt32(0))
        directory.appendLE(offset)
        directory.append(name)
    }

    let directoryOffset = UInt32(archive.count)
    archive.append(directory)
    archive.appendLE(UInt32(0x0605_4B50))
    archive.appendLE(UInt16(0))
    archive.appendLE(UInt16(0))
    archive.appendLE(UInt16(files.count))
    archive.appendLE(UInt16(files.count))
    archive.appendLE(UInt32(directory.count))
    archive.appendLE(directoryOffset)
    archive.appendLE(UInt16(0))
    return archive
}

private func crc32(_ data: Data) -> UInt32 {
    var result = UInt32.max
    for byte in data {
        result ^= UInt32(byte)
        for _ in 0..<8 {
            result = (result >> 1) ^ (result & 1 == 1 ? 0xEDB8_8320 : 0)
        }
    }
    return ~result
}

private extension Data {
    mutating func appendLE<T: FixedWidthInteger>(_ value: T) {
        var littleEndian = value.littleEndian
        Swift.withUnsafeBytes(of: &littleEndian) { append(contentsOf: $0) }
    }
}
